#!/usr/bin/env perl
# Copyright 2011 Ethrik Project, et al.
# Licensed under the 3-clause BSD.
use strict;
use warnings;
use FindBin qw($Bin);
use lib "$Bin/lib";
use Keldair;
use Test;
my $sock = $keldair->connect();
while(my $buffer = <$sock>)
{
	print "R: $buffer" if $keldair->debug;
	chomp $buffer;
	chop $buffer;
	$keldair->parse($buffer);
}

close $sock;
