#!/usr/bin/env perl
# Copyright 2011 Ethrik Project, et al.
# Licensed under the 3-clause BSD.
use strict;
use warnings;
use feature qw(say);

use Getopt::Long;
use FindBin qw($Bin);
use File::Copy::Recursive qw(rcopy fcopy); 

my ($sys, $help, $prefix);
GetOptions("sysinstall|s" => \$sys, "prefix|p=s" => \$prefix);

if ($sys) {
    say("System wide installations are not possible without root. Aborting...") and exit if $> != 0;
    my $lib = "/usr/lib/perl5/site_perl";
    $lib = "$prefix/usr/lib/perl5/site_perl" if $prefix;
    say("$lib doesn't exist. Aborting...") and exit if !-d $lib;
    my $bin = "/usr/bin";
    $bin = "$prefix/usr/bin" if $prefix;
    say("$bin doesn't exist. Aborting...") and exit if !-d $bin;
    my $etc = "/etc";
    $etc = "$prefix/etc" if $prefix;
    say("$etc doesn't exist. Aborting...") and exit if !-d $etc;
    $etc .= "/keldair.conf";
    say("Installing...");
    rcopy("$Bin/lib", $lib) and say("Successfully copied lib") or say("Couldn't copy lib: $!");
    rcopy("$Bin/bin", $bin) and say("Sucessfully copied bin") or say("Couldn't copy bin: $!");
    fcopy("$Bin/etc/example.conf", $etc) and say("Sucessfuly copied etc") or say("Couldn't copy etc: $!");
    say("Installation finished.");
}
else {
    say("No additional configuration is needed for a non-system wide install at the moment.");
}

# vim: set et sw=4 ts=4:

