#!/usr/bin/env perl
use strict;
use warnings;
use Perl::Critic;
use feature qw(say);

my $level = 1;

if (!defined $ARGV[0])
{
  say "usage: $0 <file> [level]\n";
  exit 0;
}

if (!-e $ARGV[0])
{
  say "$0: could not find $ARGV[0]";
  say "usage: $0 <file> [level]";
  exit 0;
}

$level = $ARGV[1] if ($ARGV[1] and $ARGV[1] =~ m/(5|4|3|2|1|gentle|stern|harsh|cruel|brutal)/xsm);

my $critic = Perl::Critic->new(-severity => $level);
my @violations = $critic->critique($ARGV[0]);

if (!defined $violations[0])
{
  say "$ARGV[0] passed (no violations)";
  exit 0;
}

print "Violations:\n";
my $count = 0;
say "$_" and $count++ foreach (@violations);
say "Errors: $count"
